---
abstract: 'Disqus.com API access'
author:
  - 'Ben van Staveren <madcat@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Disqus
provides:
  Net::Disqus:
    file: lib/Net/Disqus.pm
    version: v0.1.0
  Net::Disqus::Exception:
    file: lib/Net/Disqus/Exception.pm
    version: 0
requires:
  JSON::PP: 0
  LWP::UserAgent: 6.02
  Try::Tiny: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.1.0
